```
[
  { "STT": 1, "Tu_moi": "阿姨", "Phien_am": "āyí", "Giai_thich": "dì, cô, bác gái", "Vi_du_chu_han": "阿姨，您好！", "Phien_am_vi_du": "Āyí, nín hǎo!", "Dich_vi_du": "Chào dì/cô/bác ạ!", "Han_Viet": "A Di", "Dong_Am_HV_Level": "Cao" },
  { "STT": 2, "Tu_moi": "啊", "Phien_am": "a", "Giai_thich": "a (thán từ)", "Vi_du_chu_han": "啊，原来是这样！", "Phien_am_vi_du": "A, yuánlái shì zhèyàng!", "Dich_vi_du": "À, hóa ra là vậy!", "Han_Viet": "A", "Dong_Am_HV_Level": "Cao" },
  { "STT": 3, "Tu_moi": "矮", "Phien_am": "ǎi", "Giai_thich": "lùn, thấp", "Vi_du_chu_han": "他比我矮一点。", "Phien_am_vi_du": "Tā bǐ wǒ ǎi yīdiǎn.", "Dich_vi_du": "Anh ấy thấp hơn tôi một chút.", "Han_Viet": "Ải", "Dong_Am_HV_Level": "Trung Bình" },
  { "STT": 4, "Tu_moi": "爱好", "Phien_am": "àihào", "Giai_thich": "sở thích", "Vi_du_chu_han": "你的爱好是什么？", "Phien_am_vi_du": "Nǐ de àihào shì shénme?", "Dich_vi_du": "Sở thích của bạn là gì?", "Han_Viet": "Ái Hảo", "Dong_Am_HV_Level": "Cao" },
  { "STT": 5, "Tu_moi": "安静", "Phien_am": "ānjìng", "Giai_thich": "yên tĩnh", "Vi_du_chu_han": "请保持安静。", "Phien_am_vi_du": "Qǐng bǎochí ānjìng.", "Dich_vi_du": "Xin hãy giữ yên tĩnh.", "Han_Viet": "An Tĩnh", "Dong_Am_HV_Level": "Cao" },
  { "STT": 6, "Tu_moi": "把", "Phien_am": "bǎ", "Giai_thich": "cầm, nắm; giới từ", "Vi_du_chu_han": "请把门关上。", "Phien_am_vi_du": "Qǐng bǎ mén guān shàng.", "Dich_vi_du": "Xin hãy đóng cửa lại.", "Han_Viet": "Bả", "Dong_Am_HV_Level": "Thấp" },
  { "STT": 7, "Tu_moi": "班", "Phien_am": "bān", "Giai_thich": "lớp học", "Vi_du_chu_han": "我们班有二十个学生。", "Phien_am_vi_du": "Wǒmen bān yǒu èrshí ge xuéshēng.", "Dich_vi_du": "Lớp chúng tôi có 20 học sinh.", "Han_Viet": "Ban", "Dong_Am_HV_Level": "Cao" },
  { "STT": 8, "Tu_moi": "搬", "Phien_am": "bān", "Giai_thich": "chuyển, dọn", "Vi_du_chu_han": "我明天要搬家。", "Phien_am_vi_du": "Wǒ míngtiān yào bānjiā.", "Dich_vi_du": "Ngày mai tôi phải chuyển nhà.", "Han_Viet": "Ban", "Dong_Am_HV_Level": "Thấp" },
  { "STT": 9, "Tu_moi": "办法", "Phien_am": "bànfǎ", "Giai_thich": "cách, biện pháp", "Vi_du_chu_han": "我有一个好办法。", "Phien_am_vi_du": "Wǒ yǒu yī ge hǎo bànfǎ.", "Dich_vi_du": "Tôi có một cách hay.", "Han_Viet": "Biện Pháp", "Dong_Am_HV_Level": "Cao" },
  { "STT": 10, "Tu_moi": "办公室", "Phien_am": "bàngōngshì", "Giai_thich": "văn phòng", "Vi_du_chu_han": "他在办公室工作。", "Phien_am_vi_du": "Tā zài bàngōngshì gōngzuò.", "Dich_vi_du": "Anh ấy làm việc ở văn phòng.", "Han_Viet": "Biện Công Thất", "Dong_Am_HV_Level": "Cao" },
  { "STT": 11, "Tu_moi": "半", "Phien_am": "bàn", "Giai_thich": "nửa", "Vi_du_chu_han": "我吃了半个苹果。", "Phien_am_vi_du": "Wǒ chīle bàn ge píngguǒ.", "Dich_vi_du": "Tôi đã ăn nửa quả táo.", "Han_Viet": "Bán", "Dong_Am_HV_Level": "Cao" },
  { "STT": 12, "Tu_moi": "帮忙", "Phien_am": "bāngmáng", "Giai_thich": "giúp đỡ", "Vi_du_chu_han": "你能帮我一个忙吗？", "Phien_am_vi_du": "Nǐ néng bāng wǒ yī ge máng ma?", "Dich_vi_du": "Bạn có thể giúp tôi một việc không?", "Han_Viet": "Bang Mang", "Dong_Am_HV_Level": "Cao" },
  { "STT": 13, "Tu_moi": "报纸", "Phien_am": "bàozhǐ", "Giai_thich": "báo chí", "Vi_du_chu_han": "我喜欢看报纸。", "Phien_am_vi_du": "Wǒ xǐhuān kàn bàozhǐ.", "Dich_vi_du": "Tôi thích đọc báo.", "Han_Viet": "Báo Chỉ", "Dong_Am_HV_Level": "Cao" },
  { "STT": 14, "Tu_moi": "比", "Phien_am": "bǐ", "Giai_thich": "so với", "Vi_du_chu_han": "他比我高。", "Phien_am_vi_du": "Tā bǐ wǒ gāo.", "Dich_vi_du": "Anh ấy cao hơn tôi.", "Han_Viet": "Bỉ", "Dong_Am_HV_Level": "Cao" },
  { "STT": 15, "Tu_moi": "比赛", "Phien_am": "bǐsài", "Giai_thich": "thi đấu, cuộc thi", "Vi_du_chu_han": "我们去看足球比赛。", "Phien_am_vi_du": "Wǒmen qù kàn zúqiú bǐsài.", "Dich_vi_du": "Chúng tôi đi xem trận bóng đá.", "Han_Viet": "Bỉ Tái", "Dong_Am_HV_Level": "Cao" },
  { "STT": 16, "Tu_moi": "必须", "Phien_am": "bìxū", "Giai_thich": "phải, nhất định phải", "Vi_du_chu_han": "你必须努力学习。", "Phien_am_vi_du": "Nǐ bìxū nǔlì xuéxí.", "Dich_vi_du": "Bạn phải cố gắng học tập.", "Han_Viet": "Tất Tu", "Dong_Am_HV_Level": "Cao" },
  { "STT": 17, "Tu_moi": "变化", "Phien_am": "biànhuà", "Giai_thich": "thay đổi", "Vi_du_chu_han": "城市变化很大。", "Phien_am_vi_du": "Chéngshì biànhuà hěn dà.", "Dich_vi_du": "Thành phố thay đổi rất nhiều.", "Han_Viet": "Biến Hóa", "Dong_Am_HV_Level": "Cao" },
  { "STT": 18, "Tu_moi": "表示", "Phien_am": "biǎoshì", "Giai_thich": "biểu thị, bày tỏ", "Vi_du_chu_han": "他表示同意。", "Phien_am_vi_du": "Tā biǎoshì tóngyì.", "Dich_vi_du": "Anh ấy bày tỏ sự đồng ý.", "Han_Viet": "Biểu Thị", "Dong_Am_HV_Level": "Cao" },
  { "STT": 19, "Tu_moi": "宾馆", "Phien_am": "bīnguǎn", "Giai_thich": "khách sạn", "Vi_du_chu_han": "我们住在宾馆。", "Phien_am_vi_du": "Wǒmen zhù zài bīnguǎn.", "Dich_vi_du": "Chúng tôi ở khách sạn.", "Han_Viet": "Tân Quán", "Dong_Am_HV_Level": "Cao" },
  { "STT": 20, "Tu_moi": "冰箱", "Phien_am": "bīngxiāng", "Giai_thich": "tủ lạnh", "Vi_du_chu_han": "冰箱里有水果。", "Phien_am_vi_du": "Bīngxiāng lǐ yǒu shuǐguǒ.", "Dich_vi_du": "Trong tủ lạnh có trái cây.", "Han_Viet": "Băng Tương", "Dong_Am_HV_Level": "Cao" }
```